### PR TITLE
TradeMaximizer accepting InputStream and OutputStream for easier integration

### PR DESCRIPTION
**Pull request by rafacandev**
TradeMaximizer accepting InputStream and OutputStream for easier integration. With this approach it is possible to use TradeMaximizer without the command line by passing the input as InputStream and using OutputStream to get the results.

Here is an example:
```
String inputString = "(Alice) 1 : 3 2 6\n ..."; // TradeMaximizer input string
InputStream input = new ByteArrayInputStream(inputString.getBytes());
OutputStream output = new ByteArrayOutputStream();
TradeMaximizer tradeMaximizer = new TradeMaximizer(input, output);
tradeMaximizer.run();
String result = output.toString();
// Close the streams and handle exceptions normally
```

### CODE REVIEW

**Comment by chrisokasaki** [comment]
Thanks.  Just so you have some idea of timing, I won't be able to look at this carefully until next week.

**Review by chrisokasaki — CHANGES_REQUESTED** [review]
Looks good.  My only request would be to replace the tabs you've introduced with spaces.

Thanks!

**Comment by rafacandev** [comment]
Hi @chrisokasaki 

Thanks for reviewing it. No problem, I removed the introduced tabs. Don't hesitate to contact me if there are other adjustments.

Cheers.

**Review by chrisokasaki — APPROVED** [review]
Looks good.  Thanks!

**Pull request merged**
